### PR TITLE
Make example program work with Python 3.6

### PR DESCRIPTION
**Pull request by drunsinn**
Hello. This allowes the example program to run in python 3.6 (should also work in any other python 3 releases) and fixes some type-casting problems in the generation of output lines.

### CODE REVIEW

**Comment by Rod-Persky** [comment]
Thank you for your PR @drunsinn, I cannot remember how this code base works. Unfortunently it will take me some time before I can become familiar with it once again and look into this. Are you presently using pyIGES for a project?

**Comment by drunsinn** [comment]
Hello @Rod-Persky ,
yes, I want to switch some code that currently exports stl to iges since its better suitable for CAM work.

**Comment by Rod-Persky** [comment]
Ok :) that’s exactly what this was all about. STL is not suitable for parametric, surface based work.

I found at the time I wrote this that CAD packages ended up implementing IGES differently. Additionally, I was unsure of the different technical aspects of implementing this.

To confirm everything is working is simple. Drawing a hollow drum of a known dimension and measure it in a CAD package. When using the CAD package, the drum should be rendered at the expected location with the correct sizes. When I performed this test I found the drum surface, drawn using a trimmed surface, wasn’t correct.

If you need a solution fast, as I eventually did, consider OpenCASCADE and c++. I think OpenCASCADE supports some parametric formats too (x_t?). I am out of the loop with developments in computational geometry libraries, but am surprised few implementations of IGES are around given its  an open format.

**Comment by drunsinn** [comment]
I tried OpenCASCADE but decided aganst it. For my application (converting geospatial data to a 3d surface) OCC seemd a bit to involved to get running ;-). I added the rational BSpline surface which works for me. This is a rectangle of 100 x 100 Point in x and y while the z value is random:
random
 I will send you a pull request for this (and other changes) when I get time to do some cleanup!

**Comment by drunsinn** [comment]
Updated build system to distutils and shell script for sphinx

**Pull request merged**
